<script setup>
import { ref, onMounted } from 'vue';
import QRCode from 'qrcode';
import AppShell from '../components/AppShell.vue';
const events = ref([]), selected = ref(null), editing = ref(false), rows = ref({data:[]}), error = ref(''), notice = ref(''), busy = ref(false), qr = ref(''), q = ref(''), filter = ref(''), closing = ref(false);
const defaults = () => ({name:'Aulão de funcional na praia', organizer:'Team Peu', location:'Praia de Ipitanga', description:'Uma manhã para se movimentar, encontrar a comunidade e começar o dia com energia.', starts_at:'2026-10-18T06:00', ends_at:'2026-10-18T09:00', checkin_opens_at:'2026-10-18T06:00', capacity:null, status:'draft', instructions:'', after_content:''});
const form = ref(defaults());
function fail(e){error.value=Object.values(e.response?.data?.errors||{}).flat()[0]||e.response?.data?.message||'Não foi possível conectar. Tente novamente.';}
async function load(){try{events.value=(await window.axios.get('/api/events')).data;}catch(e){fail(e);}}
function publicUrl(e){return `${location.origin}/evento/${e.slug}`;}
async function choose(e){selected.value=e;editing.value=false;closing.value=false;q.value='';filter.value='';qr.value='';await registrations();if(e.status==='published')qr.value=await QRCode.toDataURL(publicUrl(e),{width:600,margin:3});}
async function registrations(page=1){try{rows.value=(await window.axios.get(`/api/events/${selected.value.id}/registrations`,{params:{q:q.value,status:filter.value||undefined,page}})).data;}catch(e){fail(e);}}
function localTime(v){if(!v)return '';const parts=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Bahia',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(v));return parts.replace(' ','T');}
function edit(e=null){selected.value=e;form.value=e?{...e,...Object.fromEntries(['starts_at','ends_at','checkin_opens_at'].map(k=>[k,localTime(e[k])]))}:defaults();editing.value=true;error.value='';}
async function save(){busy.value=true;error.value='';try{const payload={...form.value};const {data}=await window.axios[selected.value?'patch':'post'](selected.value?`/api/events/${selected.value.id}`:'/api/events',payload);await load();await choose(events.value.find(e=>e.id===data.id));notice.value='Evento salvo.';}catch(e){fail(e);}finally{busy.value=false;}}
async function attendance(row){busy.value=true;try{await window.axios.patch(`/api/events/${selected.value.id}/registrations/${row.id}`,{present:!row.checked_in_at});await registrations(rows.value.current_page);await load();selected.value=events.value.find(e=>e.id===selected.value.id);}catch(e){fail(e);}finally{busy.value=false;}}
async function close(){busy.value=true;error.value='';try{await window.axios.post(`/api/events/${selected.value.id}/close`);await load();await choose(events.value.find(e=>e.id===selected.value.id));notice.value='Evento encerrado. A avaliação está liberada para os presentes.';}catch(e){fail(e);}finally{busy.value=false;}}
async function copy(){try{await navigator.clipboard.writeText(publicUrl(selected.value));notice.value='Link copiado.';}catch{notice.value='Copie o link exibido abaixo.';}}
function status(e){return e.closed_at?'Encerrado':({draft:'Rascunho',published:'Publicado',cancelled:'Cancelado'}[e.status]);}
onMounted(load);
</script>
<template>
<AppShell eyebrow="Comunidade WNFIT" title="Eventos" description="Da primeira inscrição ao encontro com sua comunidade.">
  <template #page-actions><button class="btn-primary" @click="edit()">Criar evento</button></template>
  <div class="events-manager">
    <p v-if="error" role="alert" class="event-alert">{{ error }}</p><p v-if="notice" role="status" class="event-notice">{{ notice }}</p>
    <div class="event-layout"><aside class="event-panel"><h2>Seus encontros</h2><p v-if="!events.length">Crie o primeiro evento para começar a receber inscrições.</p><button v-for="e in events" :key="e.id" class="event-choice" :class="{'chosen':selected?.id===e.id}" @click="choose(e)"><small>{{ status(e) }}</small><strong>{{ e.name }}</strong><span>{{ e.registrations_count }} inscritos · {{ e.present_count }} presentes</span></button></aside>
    <section v-if="editing" class="event-panel"><h2>{{ selected?'Editar evento':'Novo evento' }}</h2><form @submit.prevent="save"><label>Nome<input v-model="form.name" required maxlength="150" /></label><label>Organização<input v-model="form.organizer" required maxlength="150" /></label><label>Local / ponto de encontro<input v-model="form.location" required maxlength="255" /></label><label>Apresentação<textarea v-model="form.description" maxlength="3000" /></label><div class="event-fields"><label>Início (horário da Bahia)<input v-model="form.starts_at" type="datetime-local" required /></label><label>Término previsto<input v-model="form.ends_at" type="datetime-local" required /></label></div><label>Abrir confirmação de presença em<input v-model="form.checkin_opens_at" type="datetime-local" required /></label><p>O gestor encerra o evento manualmente. O término previsto não bloqueia a presença nem libera a avaliação.</p><label>Limite de vagas (vazio = sem limite)<input v-model="form.capacity" type="number" min="1" /></label><label>Orientações para os participantes<textarea v-model="form.instructions" maxlength="3000" /></label><label>Mensagem após o encerramento<textarea v-model="form.after_content" maxlength="3000" /></label><label>Disponibilidade<select v-model="form.status"><option value="draft">Rascunho · somente prévia</option><option value="published">Publicado · abrir inscrições</option><option value="cancelled">Cancelado</option></select></label><button class="btn-primary" :disabled="busy">Salvar evento</button></form></section>
    <section v-else-if="selected" class="event-panel"><div class="event-heading"><div><small>{{ status(selected) }}</small><h2>{{ selected.name }}</h2></div><button v-if="!selected.closed_at" class="btn-secondary" @click="edit(selected)">Editar</button></div><p>{{ selected.location }} · {{ new Date(selected.starts_at).toLocaleString('pt-BR',{timeZone:'America/Bahia'}) }}</p>
      <div class="event-metrics"><div><strong>{{ selected.registrations_count }}</strong><span>Inscritos</span></div><div><strong>{{ selected.present_count }}</strong><span>Presentes</span></div><div><strong>{{ selected.registrations_count-selected.present_count }}</strong><span>Sem presença</span></div></div>
      <div class="event-sharing"><div><h3>{{ selected.closed_at?'Página e avaliações do evento':selected.status==='published'?'Convide sua comunidade':'Confira a página do evento' }}</h3><p>O QR code é para pré-inscrição. No dia, o participante volta pelo mesmo link.</p><a :href="publicUrl(selected)" target="_blank" rel="noopener" class="event-link">{{ selected.status==='draft'?'Abrir prévia':'Abrir página' }}</a><template v-if="selected.status==='published'"><button class="btn-secondary" @click="copy">Copiar link</button><a v-if="qr" class="btn-secondary" :href="qr" download="qr-evento-wnfit.png">Baixar QR code</a><input aria-label="Link público do evento" readonly :value="publicUrl(selected)" /></template></div><img v-if="qr" :src="qr" alt="QR code para pré-inscrição" width="130" height="130" /></div>
      <div v-if="selected.status==='published'&&!selected.closed_at" class="event-end"><p>Ao encerrar, novas inscrições e confirmações de presença serão bloqueadas e a avaliação será liberada.</p><button v-if="!closing" class="btn-secondary" @click="closing=true">Encerrar evento…</button><div v-else><strong>Deseja encerrar agora?</strong><button class="btn-primary" :disabled="busy" @click="close">Sim, encerrar evento</button><button class="btn-secondary" @click="closing=false">Voltar</button></div></div>
      <h3>Participantes</h3><p>Presença “pelo participante” é autodeclarada. A equipe pode revisar o registro.</p><form class="event-fields" @submit.prevent="registrations()"><input v-model="q" placeholder="Buscar nome ou telefone" aria-label="Buscar participante" /><select v-model="filter" aria-label="Filtrar presença" @change="registrations()"><option value="">Todos</option><option value="present">Presentes</option><option value="absent">Sem presença</option></select><button class="btn-secondary">Buscar</button></form>
      <p v-if="!rows.data.length">Nenhum participante encontrado.</p><article v-for="row in rows.data" :key="row.id" class="event-person"><div><strong>{{ row.name }}</strong><p>{{ row.phone }}</p><small>{{ row.checked_in_at?(row.attendance_source==='self'?'Presença pelo participante':'Presença pela equipe'):'Sem presença confirmada' }} · {{ row.marketing_opt_in?'Aceita novidades':'Somente comunicações do evento' }}</small><p v-if="row.rating">Avaliação: {{ row.rating }}/5 <span v-if="row.feedback">· {{ row.feedback }}</span></p></div><button class="btn-secondary" :disabled="busy" @click="attendance(row)">{{ row.checked_in_at?'Remover presença':'Registrar presença' }}</button></article><div v-if="rows.last_page>1" class="event-fields"><button class="btn-secondary" :disabled="rows.current_page===1" @click="registrations(rows.current_page-1)">Anterior</button><span>{{ rows.current_page }} / {{ rows.last_page }}</span><button class="btn-secondary" :disabled="rows.current_page===rows.last_page" @click="registrations(rows.current_page+1)">Próxima</button></div>
    </section><section v-else class="event-panel"><h2>Uma experiência que começa antes do encontro</h2><p>Selecione um evento ou crie o aulão do Team Peu. As inscrições são independentes do cadastro de alunos e não geram mensalidades.</p><button class="btn-primary" @click="edit()">Preparar aulão Team Peu</button></section></div>
  </div>
</AppShell>
</template>
<style scoped>
.event-layout{display:grid;grid-template-columns:260px minmax(0,1fr);gap:20px}.event-panel{background:white;border:1px solid var(--wn-line);border-radius:20px;padding:24px;align-self:start;min-width:0}.event-panel h2{font-size:20px;font-weight:750;margin-bottom:12px}.event-panel h3{font-size:16px;font-weight:700;margin:16px 0 8px}.event-panel p{font-size:13px;color:var(--wn-muted);line-height:1.7;margin:10px 0}.event-choice{display:grid;text-align:left;gap:6px;padding:16px 12px;width:100%;border:1px solid var(--wn-line);border-radius:12px;margin-top:12px}.event-choice.chosen{background:#f0f6e7;border-color:#9fbe8d}.event-choice span,small{font-size:11px}.event-panel label{display:grid;gap:8px;margin:16px 0;font-size:13px}.event-panel input,.event-panel textarea,.event-panel select{width:100%;padding:12px;border:1px solid #cbd5cd;border-radius:10px;font-size:14px;min-width:0}.event-fields{display:flex;gap:12px;align-items:center}.event-fields>*{flex:1;min-width:0}.event-heading{display:flex;justify-content:space-between;gap:12px}.event-metrics{display:flex;gap:12px;margin:24px 0}.event-metrics div{flex:1;padding:16px;background:#f3f6ef;border-radius:12px;display:grid;gap:6px}.event-metrics strong{font-size:28px}.event-metrics span{font-size:12px}.event-sharing{display:flex;align-items:center;gap:16px;padding:18px;background:#f8faf5;border-radius:14px}.event-sharing>div{min-width:0;flex:1}.event-sharing .btn-secondary,.event-end button{margin:8px 8px 8px 0}.event-link{display:block;color:#376c35;text-decoration:underline;margin:10px 0}.event-end{border-bottom:1px solid var(--wn-line);padding:16px 0}.event-person{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:18px 0;border-bottom:1px solid var(--wn-line)}.event-person p{margin:4px 0;overflow-wrap:anywhere}.event-person button{flex-shrink:0}.event-alert,.event-notice{padding:15px;border-radius:12px;margin-bottom:16px;background:#ffe8df}.event-notice{background:#eaf4e2}@media(max-width:1000px){.event-layout{grid-template-columns:1fr}.event-fields{flex-wrap:wrap}.event-fields>*{flex-basis:100%}.event-sharing{flex-direction:column;align-items:start}.event-person{align-items:start;flex-direction:column}.event-panel{padding:18px}}
</style>
