<template>
    <AppShell eyebrow="Treinos > Montador" :title="isEditing ? 'Editar treino' : 'Novo treino'" description="Organize a rotina por dias e detalhe a execucao de cada exercicio.">
        <div class="grid gap-5 xl:grid-cols-[330px_1fr]">
            <aside class="space-y-3"><section class="panel-card"><h2 class="text-lg font-semibold">Informacoes do treino</h2><div class="mt-5 space-y-4"><Field label="Nome do treino *" v-model="form.nome" placeholder="Ex.: Hipertrofia ABC" /><Field label="Objetivo *" v-model="form.objetivo" placeholder="Ex.: Hipertrofia" /><label class="block space-y-2"><span class="text-sm font-medium text-[var(--wn-muted)]">Nivel *</span><select v-model="form.nivel" class="form-control"><option value="iniciante">Iniciante</option><option value="intermediario">Intermediario</option><option value="avancado">Avancado</option></select></label><div class="grid grid-cols-2 gap-3"><Field label="Sessoes/semana" v-model="form.sessoes_semana" type="number" /><Field label="Duracao (semanas)" v-model="form.duracao_semanas" type="number" /></div><label class="block space-y-2"><span class="text-sm font-medium text-[var(--wn-muted)]">Descricao</span><textarea v-model="form.descricao" rows="4" class="form-control" placeholder="Orientacoes gerais do programa."></textarea></label></div></section>
                <div class="grid grid-cols-[auto_auto_1fr] gap-2 rounded-xl border border-[var(--wn-line)] bg-white p-3 shadow-sm">
                    <RouterLink to="/treinos" class="btn-secondary !min-h-11 !px-3" title="Cancelar" aria-label="Cancelar"><ArrowLeft class="h-4 w-4" /><span class="hidden sm:inline xl:hidden">Cancelar</span></RouterLink>
                    <button class="btn-secondary !min-h-11 !px-3" type="button" :disabled="saving" title="Salvar rascunho" aria-label="Salvar rascunho" @click="save('rascunho')"><FilePenLine class="h-4 w-4" /><span class="hidden sm:inline xl:hidden">Rascunho</span></button>
                    <button class="btn-primary !min-h-11 justify-center !px-3" type="button" :disabled="saving" @click="save('ativo')"><Save class="h-4 w-4" /><span>{{ saving ? 'Salvando...' : 'Salvar' }}</span></button>
                </div>
            </aside>

            <main v-if="currentDay" class="space-y-5">
                <div class="space-y-3">
                    <section class="panel-card !p-4"><div class="flex items-center justify-between gap-4"><div><h2 class="font-semibold">Dias do treino</h2><p class="mt-0.5 text-xs text-[var(--wn-muted)]">Selecione um dia para editar.</p></div><button class="btn-primary !min-h-9 !w-9 !justify-center !p-0" title="Adicionar dia" aria-label="Adicionar dia" @click="addDay"><Plus class="h-4 w-4" /></button></div><div class="mt-3 flex gap-2 overflow-x-auto pb-1"><button v-for="(day, index) in form.days" :key="day.key" class="flex min-w-40 shrink-0 items-center justify-between gap-3 rounded-lg border px-3 py-2 text-left text-sm transition" :class="activeDay === index ? 'border-[var(--wn-primary-strong)] bg-[var(--wn-primary-soft)]' : 'border-[var(--wn-line)] hover:border-[var(--wn-primary-strong)]'" @click="activeDay = index"><span class="font-semibold">{{ day.name || `Treino ${index + 1}` }}</span><span class="text-xs text-[var(--wn-muted)]">{{ day.exercises.length }} exerc.</span></button></div></section>
                    <section class="panel-card !p-4"><div class="flex flex-col gap-3 md:flex-row md:items-end"><div class="grid flex-1 gap-3 sm:grid-cols-2"><Field label="Nome do dia *" v-model="currentDay.name" placeholder="Ex.: Treino A" /><Field label="Foco" v-model="currentDay.focus" placeholder="Ex.: Peito e triceps" /></div><button v-if="form.days.length > 1" class="btn-secondary text-rose-600" @click="removeDay(activeDay)"><Trash2 class="h-4 w-4" />Remover dia</button></div></section>
                </div>

                <section class="panel-card p-0"><div class="flex items-center justify-between gap-4 border-b border-[var(--wn-line)] p-5"><div><h2 class="text-lg font-semibold">Exercicios</h2><p class="mt-1 text-sm text-[var(--wn-muted)]">Exercicios selecionados para este dia.</p></div><button class="btn-primary shrink-0" @click="openPicker"><Plus class="h-4 w-4" />Adicionar exercicios</button></div>
                    <div v-if="currentDay.exercises.length" class="grid gap-4 p-5 md:grid-cols-2 2xl:grid-cols-3"><article v-for="(exercise, index) in currentDay.exercises" :key="exercise.key" class="overflow-hidden rounded-xl border border-[var(--wn-line)] bg-[var(--wn-surface-soft)]"><div class="relative aspect-square border-b border-[var(--wn-line)] bg-white"><div class="absolute inset-0 grid place-items-center text-slate-200"><Dumbbell class="h-12 w-12" /></div><span class="absolute left-3 top-3 grid h-7 min-w-7 place-items-center rounded-full bg-[var(--wn-ink)] px-2 text-xs font-bold text-white">{{ index + 1 }}</span><button class="icon-button absolute right-3 top-3 text-rose-600" title="Remover exercicio" @click="removeExercise(index)"><Trash2 class="h-4 w-4" /></button></div><div class="p-4"><h3 class="font-semibold">{{ exercise.name }}</h3><p class="mt-1 text-sm text-[var(--wn-muted)]">{{ exercise.muscleGroup }}</p><div class="mt-4 grid grid-cols-2 gap-3"><Field label="Series" v-model="exercise.sets" type="number" /><Field label="Repeticoes" v-model="exercise.repetitions" placeholder="8-12" /><Field label="Carga" v-model="exercise.load" placeholder="A definir" /><Field label="Descanso (seg.)" v-model="exercise.restSeconds" type="number" /></div><div class="mt-3"><Field label="Observacoes" v-model="exercise.notes" placeholder="Cadencia ou tecnica." /></div></div></article></div>
                    <div v-else class="grid place-items-center p-12 text-center"><div><div class="mx-auto grid h-14 w-14 place-items-center rounded-xl bg-[var(--wn-primary-soft)] text-[var(--wn-primary-strong)]"><Dumbbell class="h-6 w-6" /></div><p class="mt-4 font-semibold">Nenhum exercicio adicionado</p><p class="mt-1 text-sm text-[var(--wn-muted)]">Use o botao acima para montar este treino.</p></div></div>
                </section><p v-if="message" class="rounded-lg px-4 py-3 text-sm" :class="hasError ? 'bg-rose-50 text-rose-600' : 'bg-[var(--wn-primary-soft)] text-[var(--wn-primary-strong)]'">{{ message }}</p>
            </main>
        </div>

        <div v-if="pickerOpen" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4" @click.self="closePicker"><section class="flex max-h-[88vh] w-full max-w-5xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><header class="flex items-start justify-between border-b border-[var(--wn-line)] p-5"><div><h2 class="text-xl font-semibold">Adicionar exercicios</h2><p class="mt-1 text-sm text-[var(--wn-muted)]">Clique em um exercicio para adiciona-lo ao treino.</p></div><button class="icon-button" @click="closePicker"><X class="h-4 w-4" /></button></header><div class="grid gap-3 border-b border-[var(--wn-line)] p-5 sm:grid-cols-[1fr_190px]"><label class="input-shell"><Search class="h-5 w-5 text-[var(--wn-muted)]" /><input v-model="exerciseSearch" class="auth-input" placeholder="Buscar exercicio..." /></label><select v-model="muscleFilter" class="form-control"><option value="todos">Todos os grupos</option><option v-for="muscle in muscleOptions" :key="muscle" :value="muscle">{{ muscle }}</option></select></div><div class="overflow-y-auto p-5"><div class="grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4"><button v-for="exercise in filteredExercises" :key="exercise.id" class="overflow-hidden rounded-xl border text-left transition" :class="isSelected(exercise.id) ? 'border-[var(--wn-primary-strong)] bg-[var(--wn-primary-soft)]' : 'border-[var(--wn-line)] hover:-translate-y-0.5 hover:border-[var(--wn-primary-strong)] hover:shadow-md'" @click="selectExercise(exercise)"><div class="relative aspect-square border-b border-[var(--wn-line)] bg-white"><div class="absolute inset-0 grid place-items-center text-slate-200"><Dumbbell class="h-10 w-10" /></div><span v-if="isSelected(exercise.id)" class="absolute right-3 top-3 rounded-full bg-[var(--wn-primary-strong)] px-2 py-1 text-xs font-bold text-white">Adicionado</span></div><div class="p-3"><p class="font-semibold">{{ exercise.name }}</p><p class="mt-1 text-sm text-[var(--wn-muted)]">{{ exercise.muscleGroup }}</p></div></button></div><p v-if="!filteredExercises.length" class="p-8 text-center text-sm text-[var(--wn-muted)]">Nenhum exercicio encontrado.</p></div></section></div>
    </AppShell>
</template>

<script setup>
import { computed, defineComponent, h, onMounted, reactive, ref } from 'vue';
import { RouterLink, useRoute, useRouter } from 'vue-router';
import { ArrowLeft, Dumbbell, FilePenLine, Plus, Save, Search, Trash2, X } from 'lucide-vue-next';
import AppShell from '../components/AppShell.vue';

const Field = defineComponent({ props: { label: String, modelValue: [String, Number], type: { type: String, default: 'text' }, placeholder: String }, emits: ['update:modelValue'], setup: (props, { emit }) => () => h('label', { class: 'block space-y-2' }, [h('span', { class: 'text-sm font-medium text-[var(--wn-muted)]' }, props.label), h('input', { value: props.modelValue ?? '', type: props.type, placeholder: props.placeholder, class: 'form-control', onInput: (event) => emit('update:modelValue', event.target.value) })]) });
const newExercise = () => ({ key: crypto.randomUUID(), exerciseId: null, name: '', muscleGroup: '', equipment: '', sets: 3, repetitions: '10', load: '', restSeconds: 60, notes: '' });
const newDay = (number) => ({ key: crypto.randomUUID(), name: `Treino ${String.fromCharCode(64 + number)}`, focus: '', exercises: [] });
const route = useRoute(); const router = useRouter(); const saving = ref(false); const message = ref(''); const hasError = ref(false); const activeDay = ref(0);
const catalog = ref([]); const muscleOptions = ref([]); const exerciseSearch = ref(''); const muscleFilter = ref('todos'); const pickerOpen = ref(false);
const isEditing = computed(() => Boolean(route.params.id));
const form = reactive({ nome: '', objetivo: '', nivel: 'iniciante', sessoes_semana: 3, duracao_semanas: 4, descricao: '', days: [newDay(1)] });
const currentDay = computed(() => form.days[activeDay.value]);
const filteredExercises = computed(() => { const term = exerciseSearch.value.trim().toLocaleLowerCase('pt-BR'); return catalog.value.filter((exercise) => (muscleFilter.value === 'todos' || exercise.muscleGroup === muscleFilter.value) && (!term || `${exercise.name} ${exercise.muscleGroup} ${exercise.equipment ?? ''}`.toLocaleLowerCase('pt-BR').includes(term))); });
const addDay = () => { form.days.push(newDay(form.days.length + 1)); activeDay.value = form.days.length - 1; };
const removeDay = (index) => { form.days.splice(index, 1); activeDay.value = Math.max(0, index - 1); };
const removeExercise = (index) => currentDay.value.exercises.splice(index, 1);
const openPicker = () => { pickerOpen.value = true; exerciseSearch.value = ''; muscleFilter.value = 'todos'; };
const closePicker = () => { pickerOpen.value = false; };
const isSelected = (id) => currentDay.value.exercises.some((exercise) => exercise.exerciseId === id);
const selectExercise = (selected) => { if (isSelected(selected.id)) return; currentDay.value.exercises.push({ ...newExercise(), exerciseId: selected.id, name: selected.name, muscleGroup: selected.muscleGroup, equipment: selected.equipment ?? '' }); };
const payload = (status) => ({ ...form, status, studentId: route.query.student || undefined, days: form.days.map(({ key, ...day }) => ({ ...day, exercises: day.exercises.map(({ key: exerciseKey, ...exercise }) => exercise) })) });
const save = async (status) => { saving.value = true; message.value = ''; hasError.value = false; try { const request = isEditing.value ? window.axios.put(`/api/workouts/${route.params.id}`, payload(status)) : window.axios.post('/api/workouts', payload(status)); const { data } = await request; if (route.query.student) { router.push(`/alunos/${route.query.student}?tab=workouts`); return; } router.push(`/treinos/${data.workout.id}/editar`); message.value = status === 'ativo' ? 'Treino salvo e ativado.' : 'Rascunho salvo.'; } catch (exception) { const errors = exception.response?.data?.errors; hasError.value = true; message.value = errors ? Object.values(errors).flat()[0] : 'Nao foi possivel salvar o treino.'; } finally { saving.value = false; } };
onMounted(async () => { const catalogResponse = await window.axios.get('/api/exercises'); catalog.value = catalogResponse.data.exercises; muscleOptions.value = catalogResponse.data.filters.muscles; if (!isEditing.value) return; const { data } = await window.axios.get(`/api/workouts/${route.params.id}`); Object.assign(form, { nome: data.workout.name, objetivo: data.workout.objective, nivel: data.workout.level, sessoes_semana: data.workout.sessionsPerWeek, duracao_semanas: data.workout.durationWeeks, descricao: data.workout.description ?? '', days: data.workout.days.map((day) => ({ ...day, key: crypto.randomUUID(), exercises: day.exercises.map((exercise) => ({ ...exercise, equipment: catalog.value.find((item) => item.id === exercise.exerciseId)?.equipment ?? '', key: crypto.randomUUID() })) })) }); });
</script>
